import os
from dotenv import load_dotenv

load_dotenv()

ALPACA_API_KEY = os.getenv("ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")
ALPACA_BASE_URL = os.getenv("ALPACA_BASE_URL", "https://paper-api.alpaca.markets")

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

WATCHLIST = os.getenv("WATCHLIST", "AAPL,MSFT").split(",")

MAX_POSITION_SIZE = float(os.getenv("MAX_POSITION_SIZE", 1000))
MAX_DAILY_LOSS = float(os.getenv("MAX_DAILY_LOSS", 200))
STOP_LOSS_PCT = float(os.getenv("STOP_LOSS_PCT", 0.03))
TAKE_PROFIT_PCT = float(os.getenv("TAKE_PROFIT_PCT", 0.06))
POSITION_SIZE_PCT = float(os.getenv("POSITION_SIZE_PCT", 0.20))
MAX_POSITIONS = int(os.getenv("MAX_POSITIONS", 4))
MAX_DAILY_LOSS_PCT = float(os.getenv("MAX_DAILY_LOSS_PCT", 0.05))
TRAILING_STOP_PCT = float(os.getenv("TRAILING_STOP_PCT", 0.035))

OPTIONS_ENABLED = os.getenv("OPTIONS_ENABLED", "false").lower() == "true"

ATR_PERIOD = 14
ATR_HARD_MULT = 2.5
ATR_TRAIL_MULT = 2.0
ATR_TP_MULT = 4.0

RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 70
SMA_SHORT = 9
SMA_LONG = 21
TREND_SMA = 50
BAR_TIMEFRAME = "1Hour"
LOOKBACK_BARS = 200
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL_PERIOD = 9
MIN_HOLD_BARS = 3
MAX_HOLD_BARS = int(os.getenv("MAX_HOLD_BARS", 20))
COOLDOWN_BARS = 2

BUY_LIMIT_TOLERANCE = float(os.getenv("BUY_LIMIT_TOLERANCE", 0.003))
SELL_LIMIT_TOLERANCE = float(os.getenv("SELL_LIMIT_TOLERANCE", 0.002))
STOP_INTERVAL_MINUTES = int(os.getenv("STOP_INTERVAL_MINUTES", 1))
